
### `cmd/server/docker-compose.yml`
version: '3'

services:
  server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"
